#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: check-gcc-ver

on:
  repository_dispatch:
  workflow_dispatch:
  #schedule:
    #- cron: 0 17 * * *
  # watch:
  #   types: started

env:
  REPO_URL: https://github.com/DHDAXCW/lede-rockchip
  REPO_BRANCH: stable
  CONFIG_FILE: configs/lede/full.config
  DIY_SH: scripts/lede.sh
  KMODS_IN_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      OPENWRTROOT: ${{ steps.update.outputs.OPENWRTROOT }}
      PLATFORM: ${{ steps.compile.outputs.PLATFORM }}
      TARGET: ${{ steps.compile.outputs.TARGET }}
      SUBTARGET: ${{ steps.compile.outputs.SUBTARGET }}
      FIRMWARE: ${{ steps.compile.outputs.FIRMWARE }}
      GENERATE_STATUS: ${{ steps.generate.outputs.GENERATE_STATUS }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Generate release tag
      id: tag
      run: |
          echo "release_tag=$(date +'%Y-%m-%dT%H:%M:%S')-rockchip-docker" >> $GITHUB_OUTPUT
          echo "release_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          touch release.txt
          echo "后台地址：192.168.11.1" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      if: steps.tag.outputs.status == 'success' && !cancelled()
      uses: ncipollo/release-action@main
      with:
        name: "${{ steps.tag.outputs.release_date }} openwrt-rockchip-armv8-docker 下载固件"
        token: ${{ secrets.TOKEN }}
        artifacts: "release.txt"
        bodyFile: "release.txt"
